export enum ErrorCodes {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_MISSING = 'AUTH_REFRESH_TOKEN_MISSING',
  AUTH_REFRESH_TOKEN_REVOKED = 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_INVALID_OR_EXPIRED_TOKEN = 'AUTH_INVALID_OR_EXPIRED_TOKEN',
  AUTH_EMAIL_NOT_CONFIGURED = 'AUTH_EMAIL_NOT_CONFIGURED',
  AUTH_EMAIL_SEND_FAILED = 'AUTH_EMAIL_SEND_FAILED',
  AUTH_ADMIN_REGISTER_DISABLED = 'AUTH_ADMIN_REGISTER_DISABLED',
  AUTH_ADMIN_INVITE_INVALID = 'AUTH_ADMIN_INVITE_INVALID',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  /** Delete or change would violate business rules (e.g. last admin, leads FK). */
  USER_DELETE_BLOCKED = 'USER_DELETE_BLOCKED',

  ACCESS_DENIED = 'ACCESS_DENIED',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  /** Worker / API missing DATABASE_URL or Hyperdrive — cannot reach Postgres. */
  DATABASE_NOT_CONFIGURED = 'DATABASE_NOT_CONFIGURED',

  /** DATABASE_URL set but Postgres unreachable, auth failed, or schema/tables missing. */
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',

  VALIDATION_FAILED = 'VALIDATION_FAILED',

  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  CONSULTATION_NOT_FOUND = 'CONSULTATION_NOT_FOUND',
  CONTACT_MESSAGE_NOT_FOUND = 'CONTACT_MESSAGE_NOT_FOUND',
  LEAD_NOT_FOUND = 'LEAD_NOT_FOUND',
  BLOG_NOT_FOUND = 'BLOG_NOT_FOUND',
}

